/*
 * Copyright 2005 jWic group (http://www.jwic.de)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * de.jwic.ecolib.htmleditor.HtmlEditorControl
 * Created on 27.04.2006
 * $Id: HtmlEditorControl.java,v 1.4 2010/01/25 15:23:07 lordsam Exp $
 */
package de.jwic.ecolib.controls.htmleditor;

import de.jwic.base.Field;
import de.jwic.base.IControlContainer;
import de.jwic.base.JavaScriptSupport;
import de.jwic.controls.HTMLElement;

/**
 * A WYSIWYG editing control based upon the tiny MCE javascript library. The library
 * must be included in the jwic.page file. 
 * 
 * @author Florian Lippisch
 * @version $Revision: 1.4 $
 */
@JavaScriptSupport
public class HtmlEditorControl extends HTMLElement {

	private Field field;
	
	/**
	 * Constructs a new control with an autogenerated name.
	 * @param container
	 */
	public HtmlEditorControl(IControlContainer container) {
		this(container, null);
	}
	/**
	 * @param container
	 * @param name
	 */
	public HtmlEditorControl(IControlContainer container, String name) {
		super(container, name);
		field = new Field(this);
		// default size
		setWidth(400);
		setHeight(200); 
	}

	/* (non-Javadoc)
	 * @see de.jwic.base.Control#actionPerformed(java.lang.String, java.lang.String)
	 */
	public void actionPerformed(String actionId, String parameter) {

	}

	/**
	 * Returns the field that stores the content. (Used by renderer)
	 * @return
	 */
	public Field getField() {
		return field;
	}
	/**
	 * @return
	 */
	public String getHTML() {
		return field.getValue();
	}
	
	public void setHTML(String htmlCode) {
		field.setValue(htmlCode);
		requireRedraw();
	}
}
